export type OpenF1Meeting = { meeting_key: number; meeting_name: string; meeting_official_name: string; country_name: string; location: string; circuit_short_name: string; circuit_key: number; date_start: string; date_end: string; gmt_offset?: string; year: number }
export type OpenF1Session = { session_key: number; meeting_key: number; session_name: string; session_type: string; date_start: string; date_end: string }
export type F1Session = { sessionKey: number; meetingKey: number; name: string; type: string; start: string; end: string }
export type F1Meeting = { meetingKey: number; round: number | null; name: string; officialName: string; country: string; location: string; circuit: string; circuitKey: number; start: string; end: string; timezoneOffset: string | null; year: number }
export type F1NextRace = F1Meeting & { raceSession: F1Session; sessions: F1Session[] }
export type OpenF1Driver = { driver_number: number; first_name: string; last_name: string; full_name: string; team_name: string; team_colour?: string; country_code?: string | null; country_name?: string | null; headshot_url?: string | null }
export type OpenF1DriverStanding = { driver_number: number; position_current: number; points_current: number }
export type OpenF1TeamStanding = { team_name: string; position_current: number; points_current: number }
export type OpenF1SessionResult = { position: number; driver_number: number; number_of_laps: number; points: number; dnf: boolean; dns: boolean; dsq: boolean; duration: number | null; gap_to_leader: number | null; meeting_key: number; session_key: number }
export type F1DriverStanding = { position: number; driverNumber: number; driver: string; team: string; points: number; teamColor: string | null; countryCode: string | null; nationality: string | null; imageUrl: string | null }
export type F1TeamStanding = { position: number; team: string; points: number; teamColor: string | null }
export type F1LastRaceDriver = { position: number; driverNumber: number; driver: string; team: string; teamColor: string | null; countryCode: string | null; imageUrl: string | null; status: string; time: string }
export type F1LastRace = { meetingKey: number; round: number | null; raceName: string; officialName: string; country: string; location: string; circuit: string; circuitKey: number; raceDate: string; winner: F1LastRaceDriver; secondPlace: F1LastRaceDriver | null; thirdPlace: F1LastRaceDriver | null; results: F1LastRaceDriver[] }
